"""Utilities for parsing LLM poker actions and validating them against legal moves."""

from dataclasses import dataclass
import re
from typing import Iterable, List, Optional


@dataclass
class PlayerDecision:
    """Normalized representation of a player's decision."""

    token: str                     # String to pass to PromptAdapter.apply_token (e.g. "fold", "raise_to: 400")
    action: str                    # Canonical action name ("fold", "check", "call", "raise_to", "show", "muck")
    amount: Optional[int]          # Numerical amount for raises (if applicable)
    commentary: str                # Free-form reasoning/commentary text
    raw_response: str              # Original text returned by the provider
    original_action: str           # Raw action portion before normalization


@dataclass
class LegalAction:
    """Representation of a single legal move from PokerKit."""

    kind: str                      # Canonical action name (lower case)
    raw: str                       # Raw token text from legal_tokens()
    min_amount: Optional[int] = None
    max_amount: Optional[int] = None

    def canonical_token(self) -> str:
        """Return the token string that should be passed back to PokerKit."""
        if self.kind == "raise_to":
            if self.min_amount is None:
                raise ValueError("Raise action missing min_amount")
            return f"raise_to: {self.min_amount}"
        return self.kind


class InvalidActionError(ValueError):
    """Raised when a player's response cannot be mapped to a legal action."""


def parse_player_decision(
    raw_text: str,
    legal_tokens: Iterable[str],
    game_state: Optional[dict] = None,
) -> PlayerDecision:
    """Parse and validate a raw LLM response.

    Args:
        raw_text: The raw text returned by the player.
        legal_tokens: Iterable of legal move strings generated by legal_tokens().
        game_state: Optional visible state dict for additional validation (e.g., to_call checks).

    Returns:
        PlayerDecision describing the normalized move.

    Raises:
        InvalidActionError: If the response cannot be mapped onto any legal action.
    """
    if raw_text is None:
        raise InvalidActionError("Empty response from player")

    stripped = raw_text.strip()
    if not stripped:
        raise InvalidActionError("Empty response from player")

    lines = [line.strip() for line in stripped.splitlines() if line.strip()]
    if not lines:
        raise InvalidActionError("Empty response from player")

    action_line = lines[0]
    commentary = ""

    if "@" in action_line:
        action_part, commentary_part = action_line.split("@", 1)
        commentary = commentary_part.strip()
    else:
        action_part = action_line

    original_action = action_part.strip()
    canonical_action, amount = _normalize_action(original_action)

    legal_actions = _parse_legal_tokens(legal_tokens)
    token = _validate_against_legal_actions(
        canonical_action,
        amount,
        legal_actions,
        game_state,
        original_action,
    )

    return PlayerDecision(
        token=token,
        action=canonical_action,
        amount=amount,
        commentary=commentary,
        raw_response=stripped,
        original_action=original_action,
    )


def select_fallback_token(legal_tokens: Iterable[str]) -> str:
    """Choose a conservative fallback action from the available legal moves."""
    legal_actions = _parse_legal_tokens(legal_tokens)
    if not legal_actions:
        return "fold"

    # At showdown, prefer "show" over "muck" because showing allows you to win
    # while mucking forfeits the pot. In betting rounds, prefer safer actions.
    has_showdown_options = any(action.kind in ("show", "muck") for action in legal_actions)
    if has_showdown_options:
        # At showdown: prefer show over muck (show allows winning, muck forfeits)
        # Only show and muck should be available at showdown
        if any(action.kind == "show" for action in legal_actions):
            return "show"
        if any(action.kind == "muck" for action in legal_actions):
            return "muck"
        # Fallback: should not reach here at showdown
        priority = ["show", "muck"]
    else:
        # During betting: prefer fold > check > call (safer actions first)
        priority = ["fold", "check", "call"]
    
    for desired in priority:
        for action in legal_actions:
            if action.kind == desired:
                return action.canonical_token()

    # No safe non-raise action; fall back to minimum legal raise
    for action in legal_actions:
        if action.kind == "raise_to":
            return action.canonical_token()

    return legal_actions[0].canonical_token()


def _normalize_action(action_text: str) -> tuple[str, Optional[int]]:
    """Normalize the action portion of the response."""
    lowered = action_text.lower().strip()

    if lowered in {"fold", "check", "call", "show", "muck"}:
        return lowered, None

    if lowered.startswith("raise_to"):
        match = re.search(r"raise_to\s*[: ]\s*(\d+)", lowered)
        if not match:
            raise InvalidActionError(f"Could not parse raise amount from '{action_text}'")
        amount = int(match.group(1))
        return "raise_to", amount

    # Accept responses like "raise 400"
    if lowered.startswith("raise"):
        match = re.search(r"raise\s*[: ]\s*(\d+)", lowered)
        if match:
            return "raise_to", int(match.group(1))

    # Accept "bet" as a synonym for raise
    if lowered.startswith("bet"):
        match = re.search(r"bet\s*[: ]\s*(\d+)", lowered)
        if match:
            return "raise_to", int(match.group(1))

    raise InvalidActionError(f"Unrecognized action '{action_text}'")


def _validate_against_legal_actions(
    action: str,
    amount: Optional[int],
    legal_actions: List[LegalAction],
    game_state: Optional[dict],
    original_action: str,
) -> str:
    """Ensure the parsed action is legal and return the token to apply."""
    if action == "raise_to":
        if amount is None:
            raise InvalidActionError("Raise missing amount")
        raise_actions = [la for la in legal_actions if la.kind == "raise_to"]
        if not raise_actions:
            raise InvalidActionError("Raise requested when raising is not allowed")

        for legal in raise_actions:
            minimum = legal.min_amount
            maximum = legal.max_amount if legal.max_amount is not None else minimum
            if minimum is None:
                continue
            if amount < minimum:
                continue
            if maximum is not None and amount > maximum:
                continue
            return f"raise_to: {amount}"

        # No legal raise matched
        msg_parts = []
        if raise_actions:
            ranges = ", ".join(
                _format_raise_range(la.min_amount, la.max_amount) for la in raise_actions
            )
            msg_parts.append(f"legal raise ranges: {ranges}")
        raise InvalidActionError(
            f"Illegal raise amount {amount} in response '{original_action}'"
            + (f" ({'; '.join(msg_parts)})" if msg_parts else "")
        )

    matched = [la for la in legal_actions if la.kind == action]
    if matched:
        return matched[0].canonical_token()

    # Allow 'call' when the engine presents 'check' (to_call == 0)
    if action == "call":
        if any(la.kind == "check" for la in legal_actions):
            if game_state and game_state.get("to_call", 0) == 0:
                return "check"
        raise InvalidActionError("Call requested when calling is not allowed")

    raise InvalidActionError(f"Action '{original_action}' not legal in current state")


def _parse_legal_tokens(legal_tokens: Iterable[str]) -> List[LegalAction]:
    """Convert legal token strings into structured LegalAction objects."""
    actions: List[LegalAction] = []
    for token in legal_tokens:
        if token is None:
            continue
        raw = token.strip()
        if not raw:
            continue

        lowered = raw.lower()
        if lowered.startswith("raise_to"):
            match = re.search(r"raise_to\s*:\s*(\d+)(?:\s+to\s+(\d+))?", lowered)
            if not match:
                continue
            min_amount = int(match.group(1))
            max_amount = int(match.group(2)) if match.group(2) else None
            actions.append(
                LegalAction(
                    kind="raise_to",
                    raw=raw,
                    min_amount=min_amount,
                    max_amount=max_amount,
                )
            )
            continue

        actions.append(LegalAction(kind=lowered, raw=raw))

    return actions


def _format_raise_range(min_amount: Optional[int], max_amount: Optional[int]) -> str:
    """Render a raise range for error messages."""
    if min_amount is None:
        return "unknown"
    if max_amount is None or max_amount == min_amount:
        return f"{min_amount}"
    return f"{min_amount}-{max_amount}"
